### PR TITLE
[WIP] Merge turn-based and revised battle system

### PR DESCRIPTION
**Pull request by louyihua**
A work-in-progress PR.
The goal is to merge the two types of battle systems, so that it can be changed on run-time rather than compilation time.

### CODE REVIEW

**Comment by palxex** [comment]
For refactoring we'd better have tests to ensure behavior not changed. But... let's consider how to unit-test the battle logic. Some point I thought, please append if missing:
1. fix the random generator.
2. select a fixed rpg.
3. implement a rough battle AI for both our/enemy.
4. load the rpg, run a battle in the original version, logs every turn everyone's status and forms a test-suite. HP/MP should be enough.

**Comment by louyihua** [comment]
Maybe it could be easier to just perform a unit test?
The only thing that needs to be logged is that the global variable's initial states and changes of each function call that we need to test. Then each pair of the two states can be used as a test case for the function.

**Comment by palxex** [comment]
Yeah, seems I thought too complex. Unit-tests should be OK for it. In addition, we need to ensure that every important ( changed? ) path of tested function is covered in tests, for that we may need to test every function several times with different specified initial state( and fixed random generator ).

**Comment by CecilHarvey** [comment]
I think the ATB stuff can go away now (was my experimental idea & does not provide good experience on touch-screen platforms).
Anyone interested can just download an older version.

**Comment by louyihua** [comment]
If we decide to drop support for it, maybe we should first make this feature deprecated in master for now and leaves a branch that contains the current code. Then maybe one day we can drop it permanently or maybe we can find a new, better implementation.

**Pull request closed without merging**
