### PR TITLE
Adding SDL2 Support for macOS 10.05-10.10 platforms.

### PR DESCRIPTION
**Pull request by ShikiSuen**
- [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same change?

Checked. No conflicts.

- [X] Have you added an explanation of what your changes do and why you'd like us to include them?

1. The application icon looks as ugly as hell. Also, regarding the font of the original game title, their font vendor company was closed decades ago.
2. SDL1 makes no advantages for macOS 10.05-10.10 platforms but only reduced video performances, hence the essense of implementing SDL2.
3. The rewritten README.md provides detailed instruction of how to compile targeting macOS, plus instructions of compiling on macOS using MinGW targeting Windows NT platforms.

- [X] How many dependencies was introduced in this PR? Did the minimal requirement changed, for which platform?

Removed the dependencies of SDL1 for builds targeting macOS 10.06-10.10 platforms.

- [X] Have you written new tests for your changes?

Yes.

- [X] Have you successfully run it with your changes locally?

I tested that the built macOS app (via Pal_PreMetal.xcodeproj) is executable on macOS 10.07-10.14, and Paizhangpi tested that it is executable on macOS 10.06 Snow Leopard. Further tests on macOS 10.05 is planning. Also, builds through MinGW on macOS are executable on Windows 10 LTSC 2019.

- [x] Have you tested on following platforms?
  - [X] Win32
  - [ ] UWP
  - [ ] Linux
  - [ ] Android
  - [X] macOS
  - [ ] iOS

### CODE REVIEW

**Comment by ShikiSuen** [comment]
我忘记给新的 Pal_PreMetal.xcodeproj 写 Travis 了，不过意义不大…… Travis 最低系统只到 Yosemite，且 Travis 那边能否安装 macOS 10.07 SDK 都还很难讲。

**Comment by louyihua** [comment]
Some suggestions:
1. There is no need to emphasize the word 'NT', since last non-NT kernel Windows was released 20 years ago. Moreover, many may even not know what is 'NT' now.
2. Since the build instructions for macOS is more specific, I suggest move it before generic Linux/Unix build instructions.

**Comment by ShikiSuen** [comment]
Some other notes:

1. In my README.md at this moment, the way of installing SDKs may be unacceptable by certain people (despite that I verified that they are genuine from Apple). In this case, the following alternative way of installing old SDKs may be better: https://github.com/devernay/xcodelegacy 'cause it downloads files from Apple official web server and extract the SDKs to the right place.

2. I noticed the differences between Apple GCC 4.0 and Apple GCC 4.2 from this project: https://github.com/devernay/macportsGCCfixup ... Maybe it is possible to compile Non-Metal releases (using macOS 10.07 SDK) under Metal macOS Environment (e.g. macOS 10.11 or above). Still, further investigations are necessary.

**Comment by ShikiSuen** [comment]
> Some suggestions:
> 
> 1. There is no need to emphasize the word 'NT', since last non-NT kernel Windows was released 20 years ago. Moreover, many may even not know what is 'NT' now.
> 2. Since the build instructions for macOS is more specific, I suggest move it before generic Linux/Unix build instructions.

Thanks for the comment.

Your opinions are all towards the `README.md`, and I agree that my edit towards this file needs more improvements. Since I don't know how to edit a pending pull-request, I guess you members may either edit the contents of this pull-request or omit changes to README.md .

P.S.: I would like to see new nightly builds available at bintray. I suspect that something weird is happening with my building environment. See Issue https://github.com/sdlpal/sdlpal/issues/141 and https://www.bilibili.com/video/av44713073/ .

**Comment by emumusicfan** [comment]
You could simply update your branch and GitHub PR traces it automatically. I think it is better to make a new branch and commit the changes, just for the PR.  
Have you noticed the Wiki? Perhaps it is a better idea to write the advanced build guide there. 
Would you like to make this PR dedicated for legacy Mac OS X support and leave the Icon update in another PR?

**Comment by PalMusicFan** [comment]
Maybe the build guide for legacy Mac OS X is a bit too complex for a readme section? Actually I prefer a simple and clear Readme.md. I believe a build guide for recent macOS is enough for the first step of most mac OS users interested in SDLPal.  Those who want to build SDLPal for legacy Mac OS X may read a advanced guide in the Wiki.

**Comment by ShikiSuen** [comment]
@PalMusicFan What about making the build instructions for macOS into a standalone MD file?
@emumusicfan At this moment I know less about how to make multiple PRs at the same time addressing different updates. I worry that it may matter if sequencing them incorrectly.

**Comment by ShikiSuen** [comment]
At this moment we'd better figure out "what is approvable, what is not" among the contents I pushed in this pull request. After we figure it out, I close this pull request and only push the approved ones.

**Comment by palxex** [comment]
IMHO functional PRs are better, instead of monolithic.
In my view, the changes is mainly in 3 part - correct me if I understand wrong:)
1. The new icon. It's well( in fact, excellent ), could be sliced as a single PR; just make sure the lacking part is completed - Android, UWP, Linux( if possible, unsure whether a cross-DE solution exists ). 
2. a Metal-less macOS Xcode project, by using old SDL( since SDL 2.0.9 introduced Metal/Vulkan dependency). I think it's better not introducing it in master. We've dropped many legacy systems: Symbian S40, PSP, Windows 9x, WP8, Win8 RT, iOS8-; I see no difference on non-latest macOS. Users who needs those legacy builds could fork sdlpal and maintain in their own fork (like PSV fork and , and send PR back - if it does not affect the master maintenance( since it needs old SDKs, it would ). The master should always living on bleeding edge for each supported platforms, which is the best practice for keeping portable. 
3. New detailed document on building. It's GREAT 👍 . But as @PalMusicFan mentioned, since documents could growing rapidly, if we keeps inserting them in source repo, it will makes code commits growing too; Wiki should be a better place for them, it uses a separate git repo. Since we've not decided whether wiki should be able to modify by everybody, just upload it( the markdown file, and suggested title in guide page ) here.

**Comment by ShikiSuen** [comment]
@palxex The SDL2.0.9 Framework is usable in macOS 10.5-10.10 despite that the compilation itself has to be made using macOS 10.11 SDK or above.

I am reconstructing my development environment on my laptop. It certainly needs some time. Also, I would like to see whether the Travis_ci can install old SDKs into it.

**Comment by ShikiSuen** [comment]
I am closing this pull request now because I have to rebuilt the xcodeproj ('cause there might be a problem with it).

**Pull request closed without merging**
