### PR TITLE
Download zipped game resource file

### PR DESCRIPTION
**Pull request by louyihua**
Allows downloading 'pal98rqp.zip' form baiyou100.com.
Current status:

- [x] Windows Runtime
- [ ] Android
- [x] iOS

### CODE REVIEW

**Comment by CecilHarvey** [comment]
Cool!

Anyway, IMO it would be better to only allow user-specified URL (and not pre-defined baiyou URL) for Android & iOS versions (if this is going to be added for Android & iOS).

**Comment by ShikiSuen** [comment]
百游的资源有个问题就是直接下载的话速度可能会非常慢。只有迅雷才能秒下得动。
我托轩辕剑小编帮忙转交给蔡明宏一封信请他们提供 GitHub 分流，但也不知小编有没有帮转。

**Comment by ShikiSuen** [comment]
The following download script works on macOS:

```
 mkdir ~/Desktop/DownTemp
 wget -qO- http://download.baiyou100.com/Pal98rqp.zip | tar xvz - -C ~/Desktop/DownTemp
```

**Comment by ShikiSuen** [comment]
Due to the low connection speed to the Baiyou server, the following command omits certain files unnecessary to SDLPal:
```
wget -qO- http://download.baiyou100.com/Pal98rqp.zip | tar xvz - --exclude='./*.AVI' --exclude='./HomePage.PAL' --exclude='./*.dll' --exclude='./*.DLL' --exclude='./*.ini' --exclude='./*.exe' --exclude='./*.ico' -C ~/Desktop/DownTemp 
```
You may want to remove one of the dll exclusion from the command above. However, `tar` on macOS is case-sensitive.

**Comment by palxex** [comment]
Closing due to too old.

**Pull request closed without merging**
