### PR TITLE
Native midi wrappers completion

### PR DESCRIPTION
**Pull request by palxex**
- [x] Win32
- [x] UWP
- [ ] Linux ( timidity? )
- [x] Android
- [x] macOS
- [x] iOS

### CODE REVIEW

**Comment by louyihua** [comment]
Native MIDI support for UWP is ready now.

**Comment by louyihua** [comment]
@palxex 
It would be better to move platform-specific native midi files into platform-specific directories. I've done the works for platforms other than macOS/iOS. For macOS and iOS cases, the `native_midi_osx.c` can be moved into macOS directory and a symbol link can be added in the iOS directory.

**Comment by palxex** [comment]
@louyihua Once UWP is ready please merge this PR, I cannot test it recently.

**Comment by louyihua** [comment]
OK. The linux support will be deferred. Merge.

**Pull request merged**
