### PR TITLE
Show git revision

### PR DESCRIPTION
**Pull request by louyihua**
For better debugging support, the git revision should be displayed somewhere.
Currently, for PC operating systems, we can display it on game window's title bar.
- [x] Windows Destkop
- [x] Linux

However, for other platforms, we use the configuration GUI:
- [x] Windows Runtime
- [x] Android

### CODE REVIEW

**Comment by palxex** [comment]
Er...A question: what will be showing if user download code via github's zip service, and compiled?

**Comment by louyihua** [comment]
Like this:
default

**Comment by louyihua** [comment]
The git revision is composed by the following parts:
<Git tag>-<commit count starting from the tag>-g<current commit ID>

**Comment by louyihua** [comment]
Now, if git is unavailable, the git revision will be replaced by the last modification time of `.gitignore`, which should be the same as the time of last commit (UTC -7:00) if user downloads zipped code from Github.
default

**Pull request merged**
