### PR TITLE
add opus support by importing libopusfile

### PR DESCRIPTION
**Pull request by soarqin**
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same change?

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
    * Added opus support, for music & CD play with better quality in same bitrate.
I have only changed makefiles for win32 msys/mingw, linux and wii. Other platforms need more changes to their build system, I just set PAL_HAS_OPUS to 0 by default now, so that other platforms can still get SDLPAL built without opus support.
- [x] How many dependencies was introduced in this PR? Did the minimal requirement changed, for which platform?
    * all required files from libopus and opusfile are added to source tree, so no new deps are introduced.
- [ ] Have you written new tests for your changes?

- [x] Have you successfully run it with your changes locally?

- [x] Have you tested on following platforms?
  - [x] Win32
  - [ ] UWP
  - [x] Linux
  - [ ] Android
  - [ ] macOS
  - [ ] iOS

### CODE REVIEW

**Comment by palxex** [comment]
Looks great! But for make fully use of CI, let's enable it by default.

**Comment by soarqin** [comment]
enabling it would cause VS/iOS/macOS build failed, I do not have dev env to add files to their projects at present

**Comment by palxex** [comment]
Patch for macOS/iOS/Android/AppImage
[opus-nix.patch.txt](https://github.com/sdlpal/sdlpal/files/3973602/opus-nix.patch.txt)

**Comment by soarqin** [comment]
@palxex great job, I think you should also use gConfig.pszGamePath as prefix for ogg file opening

**Comment by palxex** [comment]
@soarqin In fact oggplayer utilized UTIL_OpenFile, which already did this:) Opus player uses its internal file descriptor so we've to do it explicitly.

**Comment by soarqin** [comment]
@palxex ah, forgot that, hah

**Comment by palxex** [comment]
For the lacking platforms:
1. VS2017(win32/UWP）：wait other maintainer who has the IDE helps( I only have VS2019 )
2. 3ds: let's modify the makefile adds it, or wait the 3ds maintainer @zephray 
3. emscripten: let's modify the makefile adds it, or leave it without opus like the macOS SDL1 build( via -DPAL_HAS_OPUS=1 ), since emscripten ports also lacks this library too.
After all CI builds passes, let's merge it. 
Thanks in advance!

**Comment by soarqin** [comment]
@palxex 3ds port did not get ogg support even, so I disabled opus as well.
emscripten does not have native opus support, so that I also disabled opus in its `pal_config.h`.
MSVC project gets conflict with same filename of main files and libopusfile lib files, we may have to add a subproject to satisfy its strange naming rule. I think we just disable opus for MSVC so that all CI checks are passed.

**Comment by palxex** [comment]
Seems OK, at least for now... Please rebase the patchset to master and recommit.

**Comment by soarqin** [comment]
rebased

**Pull request merged**
