### PR TITLE
商店中商品的现有数应该包括角色身上已装备的数量。

### PR DESCRIPTION
**Pull request by liuzhier**
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same change?

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?

- [ ] How many dependencies was introduced in this PR? Did the minimal requirement changed, for which platform?

- [x] Have you written new tests for your changes?

- [x] Have you successfully run it with your changes locally?

- [x] Have you tested on following platforms?
  - [x] Win32
  - [ ] UWP
  - [ ] Linux
  - [ ] Android
  - [ ] macOS
  - [ ] iOS

- [x] I certify that I have the right and agree to submit my contributions under the terms of GNU General Public License, version 3 (or any later version at the choice of the maintainers of the SDLPAL Project) as published by the Free Software Foundation.

### CODE REVIEW

**Comment by palxex** [comment]
代码看起来不错；已确认原版遵循同样逻辑（测试用例：在白河村买柳叶刀）。

**Comment by PalMusicFan** [comment]
建议提交信息修改为：
`fix: include equipped items when counting quantities of held items in the shop`

**Comment by PalMusicFan** [comment]
建议分支名修改为：
`pr_fix_held_item_quantities`

**Comment by PalMusicFan** [comment]
仔细探讨了一下，分支名不要改了，以免重开PR。不用merge合并的话分支名也不会合并进来。
改提交信息吧：
fix: include equipped items when counting quantities of held items in the shop

**Comment by PalMusicFan** [comment]
约定式提交规范要求提交信息第一行结尾不加句号。

这次提交要不要遵守这个规范……大家讨论一下？

**Pull request merged**
