### PR TITLE
avi support for Win95 version

### PR DESCRIPTION
**Pull request by CecilHarvey**
This adds AVI support for Win95 version. Only the AVIs in the original version (including the Baiyou version) are supported (DivX-compressed AVIs in some bootleg versions are NOT supported).

Reason for not using FFmpeg = less portable & too bloated (requires non-trivial work on Android/iOS/WinPhone/PSP/Wii/...).

Note that I don't have a Windows machine (except a VPS) so I'm not able to update the Visual Studio project files for now. Someone should update the VS project before merging this :)

### CODE REVIEW

**Comment by CecilHarvey** [comment]
@louyihua @palxex Please review.

**Comment by palxex** [comment]
👍 Verified works well on iOS/macOS/android/win32 msys/mingw/ubuntu. OK to merge.

**Comment by louyihua** [comment]
A very good work!
But, it causes crash when the AVI file is illegally formatted or does not use the original format.

**Comment by louyihua** [comment]
I'm working on refactoring it to adapter incorrect conditions.

**Comment by louyihua** [comment]
Make WIN95 ending more flexible:
If 5.avi fails to play, fall back to corresponding part of DOS version ending.
If 6.avi fails to play, fall back to corresponding part of DOS version ending.

**Pull request merged**
