### PR TITLE
Google Test Integration

### PR DESCRIPTION
**Pull request by palxex**
Just made a small testsuite for PAL_swprintf, seems should be easy to expand to other utility functions.
Currently 3 way tested for invoking the unit tests:

1. linux/mingw: UNIX/WIN32(MINGW) Makefile patched, so just `make check`
2. macos: either `make check` like other UNIX, or select the PalTests Scheme in XCode Project and run Test.
3. Visual Studio: build the 'sdlpal-test' project, and run it in cmd or integrated shell. 

Since I'm not familiar with Visual Studio, failed to get it working with VS extension Google Test Adapter( and gain native support of VS live unit testing/code coverage test ), need help from Visual Studio gurus:) @louyihua

### CODE REVIEW

**Comment by louyihua** [comment]
Looks good, but a bit more complex:)
Instead of adapting the test framework on different platforms, I think maybe we could just adapter the test framework for linux platform so that the travis-ci platform to do the test when a push/PR happens. This may be easier for maintenance.

**Comment by palxex** [comment]
Yeah, really a bit complex:) In fact the current solution already able to invoke `make check` in CI script to check the testsuites, just pushed a demo.
The reason why I also want keep local unit-test as easy as possible is, it will makes the debugging the testsuites more easily, since testsuites are shared between all platform; and more important, will makes local refactoring a lot safer.

**Comment by louyihua** [comment]
I've tried to simplify the visual studio project files & makefiles.
For now, the unit test can be triggered from original `main()` if the marco `UNIT_TEST` is defined. So there is no need for a separate Visual Studio project file. Also, the makefile is simplified.

**Comment by palxex** [comment]
Great! Added some tweak to make the test exe able to direct run without launch settings to fit xUnit specification.
Wait for @CecilHarvey's review for whether merge it.

**Comment by louyihua** [comment]
@palxex Just be curious, why there are two bat files inside the win32/tests directory?

**Comment by palxex** [comment]
In fact they're needed by Google Test Adapter, an extension to integrate
google test with Visual Studio's built-in testing feature. But I havn't
able to make it works.

2017年2月27日 下午4:32，"Yihua LOU" <notifications@github.com>写道：

@palxex <https://github.com/palxex> Just be curious, why there are two bat
files inside the win32/tests directory?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sdlpal/sdlpal/pull/6#issuecomment-282657627>, or mute
the thread

**Comment by louyihua** [comment]
Oh, I see. Maybe we can just left it for future plans. For now, I think the individual test should be ok.

**Comment by palxex** [comment]
Okay, lets remove them for now. Not in front of computer, could you do it?

2017年2月27日 下午4:53，"Yihua LOU" <notifications@github.com>写道：

**Comment by louyihua** [comment]
OK. I've committed.

**Comment by CecilHarvey** [comment]
looks good to me.

**Comment by palxex** [comment]
OK, merged.

**Pull request merged**
