### PR TITLE
Optimize RLEBlit functions

### PR DESCRIPTION
**Pull request by M-HT**
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same change?

- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
       Changes are optimizations of RLEBlit functions. The original versions use division and modulo for every drawn pixel, which is very ineffective. Also clipping was done for every drawn pixels.

- [ ] How many dependencies was introduced in this PR? Did the minimal requirement changed, for which platform?

- [ ] Have you written new tests for your changes?

- [x] Have you successfully run it with your changes locally?

- [x] Have you tested on following platforms?
  - [ ] Win32
  - [ ] UWP
  - [x] Linux
  - [ ] Android
  - [ ] macOS
  - [ ] iOS

### CODE REVIEW

**Comment by palxex** [comment]
For refactoring, please add relative test cases ( demoed in tests folder ) to avoid unexpected behavior changes introduced.

**Comment by M-HT** [comment]
On what data should the RLEBlit functions be tested ?
Should I extract one or more bitmaps from the game data and put them into tests ? Is that OK ?

**Comment by palxex** [comment]
It’s OK. Just ensuring in corner cases the refactoried code have exactly same output than before.

**Comment by M-HT** [comment]
I added test cases for RLEBlit functions. Hope it's enough.

**Comment by palxex** [comment]
Excellent work. Thanks for contributing! 👍

**Pull request merged**
