### PR TITLE
A new log framework

### PR DESCRIPTION
**Pull request by louyihua**
The previous log framework is FILE-based, which is not so useful in many situations.
The new log framework turns the log system into a platform-independent part and a platform-dpendent part: the independent part converts log calls into strings, and the dependent part is responsible for outputing them. To connect these two parts, a callback-model is defined, which means each platform can implement its log output callback function. The function should be defined as follows:
```c
void log_output_callback_function(LOGLEVEL level, const char *full_log, const char *user_log);
```
In which, `level` is the level user passed in for log output, `full_log` points to a string that contains log time & log level, and `user_log` just points to what the user want to output by making the call to `UTIL_LogOutput`.
Current implementation status:
- [x] Windows (through `OutputDebugString`)
- [x] Linux (through `syslog`)
- [x] Android (through `_android_log_print`)
- [x] iOS (through `NSLog`)
- [x] macOS (through `NSLog`)

### CODE REVIEW

**Comment by palxex** [comment]
Good Job.
If I does not misunderstand, the current implementation limits logging ability in debug builds to prevent performance impacting in critical situation? But in many situation power users also needs logged info for figuring problems, and (maybe) don't want to always run in debug mode. My suggestion is add a LogLevel option in cfg( and makes it default to ERROR), let the final user to choose it.

**Comment by louyihua** [comment]
Changing log-level at runtime does sense to me too, it may improve the efficiency of debugging a release package as no rebuilding is needed.

**Comment by palxex** [comment]
Seems travis-CI experiences bug, which makes the push check done but pr check failed in same commit. Let's ignore it.

**Comment by louyihua** [comment]
Re-based the PR on latest master.
If checks passed, merge it.

**Comment by palxex** [comment]
OK. Will never try github's web-based conflict resolver again - - almost made a whole mess. Rebase is far more reasonable for doing it.

**Pull request merged**
