### PR TITLE
Filter System via GLSL

### PR DESCRIPTION
**Pull request by palxex**
Since native resolution of original PAL is very low for modern platforms, a filter system will help users much, both on scaling and more effects. 

But due to we've introduced ADLIB emulation/arbitrary resampling, which both cost CPU heavily, adding another soft filter system will costs more CPU, while lefts GPU idling on most systems. 

This PR is a new approach of implementing a filter system on GPU side, initially inspired by [sdl2glsl](AugustoRuiz/sdl2glsl). After much code rewritten and added, now it's available on all GL/GLES2 compatible platforms, which means most platforms that SDL2 supports( Win32/UWP via ANGLE/Linux/macOS/iOS/Android/webGL tested ).

Currently, the expected result is directly reuse [RetroArch GLSL Shaders](https://github.com/libretro/glsl-shaders/), and we can manually write glsl following the spec in the above URL, as demoed in shaders folder. Since this PR doesn't included GLSLP support (the multiple-pass system RetroArch supported, which could be added later ), only 1-pass shaders, like 2xsal/4xbrz/crt-easymode are supported now.

This PR also supports color calibration on macOS/iOS9.3+ ( #77, as on other platform OpenGL is always assumed using sRGB ). The macOS part can only be archived by patching SDL, which has been proved could easily porting to latest SDL source. For ease of introducing new rendering backend in the future, this PR also introduced a runtime backend switching mechanism like SDL2 itself.

sdlpal.cfg options changed in this PR( GUI not included ):
1. `EnableGLSL` enable the new GLSL based filter system, and force the window create in OpenGL mode. Turn it off(Which is default) will makes the behavior exactly as same as before; on platforms that doesn't explicitly states supporting it, this option is simply ignored.
2. `Shader` specifies the shader filename, like 2xsal.glsl. The shader file should be placed in $GamePath.
3. ~~AspectRatio~~ replaced by
```
TextureWidth
TextureHeight
```
These two options specified RTT texture size( implies the aspect ratio too ). On old GPUs, fullscreen scaling shader may be unacceptable slow. With this new size specification we can both archive a better scaling result and keep performance acceptable. Of course you can even specify it much higher on high-end platforms for supersample anti-aliasing - just don't exceed GL_MAX_TEXTURE_SIZE on your device, which is available in debug log.
4. `EnableHDR` enable experimental HDR rendering.

Test packages are available at [glsl_test](../releases/tag/glsl_test). Thanks to @PalMusicFan for both testing and reviewing.

Waiting for Review:)

### CODE REVIEW

**Comment by palxex** [comment]
Notes for android tester: recent commits on master introduced configuration redirection; example( assume your sdlpal folder in /sdcard/sdlpal ):
`adb shell touch /sdcard/Android/data/com.sdlpal.sdlpal/files/.force_external_data` enable it, then you can just modify /sdcard/sdlpal/sdlpal.cfg to test shaders.

**Comment by PalMusicFan** [comment]
Now the following glsl files are compatible. 

anti-aliasing/shaders/fxaa.glsl
crt/shaders/crt-cgwg-fast.glsl
crt/shaders/crt-easymode.glsl
ddt/shaders/ddt.glsl
sabr/shaders/sabr-hybrid.glsl
sabr/shaders/sabr-v3.0.glsl
xbr/shaders/xbr-lv2.glsl
xbr/shaders/xbr-lv3.glsl
crt/shaders/crt-aperture.glsl 
crt/shaders/crt-nes-mini.glsl 
deblur/shaders/3d-2d-mixed.glsl 
denoisers/shaders/fast-bilateral.glsl
handheld/shaders/dot.glsl 
handheld/shaders/lcd3x.glsl 
pal/shaders/pal-r57shell.glsl 
pal/shaders/pal-singlepass.glsl 
retro/shaders/bevel.glsl 
retro/shaders/sharp-bilinear-scanlines.glsl 
retro/shaders/sharp-bilinear-simple.glsl
retro/shaders/smootheststep.glsl
scalehq/shaders/2xScaleHQ.glsl 
scalehq/shaders/4xScaleHQ.glsl 
xsoft/shaders/4xsoftSdB.glsl 

anti-aliasing/shaders/advanced-aa.glsl
xbrz/shaders/4xbrz.glsl
xbrz/shaders/5xbrz.glsl
xbrz/shaders/6xbrz.glsl
xsal/shaders/2xsal.glsl
eagle/shaders/supereagle.glsl
scalenx/shaders/scale2x.glsl
scalenx/shaders/scale2xplus.glsl
scalenx/shaders/scale3x.glsl

The complete list is in the attached file.  
[SDLPal_GLSL_stat01.txt](https://github.com/sdlpal/sdlpal/files/1870145/SDLPal_GLSL_stat01.txt)

**Comment by palxex** [comment]
Current showstopper: on Cubieboard devkit, both Android 4.0/Cubian, enableGLSL=1 will shows black screen even with plain.glsl, while enableGLSL=0 works well with original SDL 2.0.8. Since this platform is targeted(GLES2/GLSL1),  it may implies deeper problem on current implementation.
Don't have enough free time working on it until middle of the month, sorry for it. Will rebase then for conflict resolving.

**Comment by louyihua** [comment]
@palxex Confirmed GUI codes, added GUI codes for Win32/Linux.

**Pull request merged**
