### PR TITLE
Fix 3DS port build error, enable travis-ci for 3DS port

### PR DESCRIPTION
**Pull request by zephray**
This should fully fix issue #95 , also fix the Makefile problem mentioned but not fixed in #81. This also enable travis-ci for 3DS port.

### CODE REVIEW

**Comment by palxex** [comment]
Could you please squash the fixing commits in order to make it clear? Thanks.

**Comment by zephray** [comment]
Yes, I will open a new PR after squashing them.

**Comment by palxex** [comment]
A little tip: you can open a separate branch for PR, and do anything you need in the branch:) Github PR will work well even after force pushing.

**Comment by zephray** [comment]
That is nice, I though force pushing would break PR

**Pull request closed without merging**
